name: Update F1 Winner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install fastf1==3.4.5 requests-cache==1.2.0 pandas==2.2.2 numpy==1.26.4

      - name: Run updater (primary Ergast)
        env:
          ERGAST_URL: https://ergast.com/api
        run: |
          set -e
          python tools/f1_winner.py || \
          (echo "::warning::Primary failed, retrying with mirror…" && \
           ERGAST_URL="https://ergast.com/api" ERGAST_MIRROR="https://ergast-api.vercel.app/api" python tools/f1_winner.py)

      - name: Show JSON (debug)
        run: cat data/latest.json

      - name: Commit JSON to this branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/latest.json
          git commit -m "data: update latest F1 winner" || echo "no changes"
          git push
